### ISSUE TITLE
Configure celery beat for scheduled tasks

### ISSUE THREAD

**Issue by devraj** [anomaly/lab-python-server#29]
Our `docker-compose` configuration has always been missing `celery beat` we should provide a template for running `beat` with async support to go with #21 

```
celery-beat:
    build: ./project
    command: celery -A core beat -l info
    volumes:
      - ./project/:/usr/src/app/
    depends_on:
      - redis
```

Also see #30
