### ISSUE TITLE
Can a single Docker image serve different purposes api, worker by overriding the command on docker-compose

### ISSUE THREAD

**Issue by devraj** [anomaly/lab-python-server#30]
At the moment we build three images purely to use the same Python package but different entry points. While researching how to use `celery beat` it occurred to me that the same `worker` should be used and there should not be a need to build a new image.

I read up on various articles and it's possible to commit the `ENTRYPOINT` and `CMD` portions in the `Dockerfile` and provide them in the `docker-compose` as a `command` directive

```
celery-beat:
  build: ./project
  command: celery -A core beat -l info
 ```

The Docker best practices article also demonstrates the proper use of `ENTRYPOINT` and `CMD`

```
ENTRYPOINT ["s3cmd"]
CMD ["--help"]
```

where `s3cmd` is the command that the container runs where as `--help` is the default parameters provided to the container.

We need to know what affect this has when using Kubernetes, but well worth the investigation as it would mean we would be down to a single image per image.

Reference articles:
- [Handling Periodic Tasks in Django with Celery and Docker](https://testdriven.io/blog/django-celery-periodic-tasks/)
- [Dockerizing Django with Postgres, Gunicorn, and Nginx](https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/)
- [Best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

**Comment by devraj** [comment]
Refactored configuration from a current WIP, also note the `depends_on` has been updated:

```
  # Applicaiton API:
  # - In development we read secrets from .env.development
  # - Provides a FastAPI based API that runs using uvicorn in development
  api:
    container_name: ${PROJ_NAME}-api
    build:
      context: .
      dockerfile: Dockerfile.api
    command: "uvicorn acacia.api:app --host=0.0.0.0 --port=80 --root-path=/api --reload"
    env_file:
      - .env.development
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src/acacia:/opt/acacia
    depends_on:
      - redis
      - db


  # Worker: is a celery based worker process that runs in the background
  worker:
    container_name: ${PROJ_NAME}-worker
    build:
      context: .
      dockerfile: Dockerfile.api
    command: "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery --app=acacia.celery.app worker --pool=gevent --loglevel=INFO --queues=celery"
    env_file:
      - .env.development
    restart: unless-stopped
    volumes:
      - ./src/acacia:/opt/acacia
    depends_on:
      - redis

  beat:
    container_name: ${PROJ_NAME}-beat
    build:
      context: .
      dockerfile: Dockerfile.api
    command: "celery --app=acacia.celery.app beat --loglevel=INFO"
    env_file:
      - .env.development
    restart: unless-stopped
    volumes:
      - ./src/acacia:/opt/acacia
    depends_on:
      - redis
```

requires you to drop `EXEC` and `CMD` from the `Dockerfile`

**Comment by devraj** [comment]
Worth reading [this section](https://kubernetes.io/docs/concepts/configuration/_print/#pg-436057b96151ecb8a4a9a9f456b5d0fc) in Kubernetes configuration spec
```
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
```
