### ISSUE TITLE
Add handy python or other shell sessions inside the container as a task

### ISSUE THREAD

**Issue by devraj** [anomaly/lab-python-server#36]
Sometimes its handy to get a Python shell to try things like `stripe` actions or http requests for other APIs. it will be handy to have a `task` command that could kick this off for us e.g:

```yaml
  dev:pyshell:
    desc: get a python session into the api docker image
    cmds:
      - docker compose exec api sh -c "python"
  dev:psql:
    desc: postgres shell on the db container
    cmds:
      - docker compose exec db sh -c "psql -U postgres"

```

and document and promote this on the `README`
