### ISSUE TITLE
Define and implement a health check endpoint

### ISSUE THREAD

**Issue by devraj** [anomaly/lab-python-server#4]
The API should provide a health check endpoint for the live environment to use and establish if a container is healthy enough to service requests, to establish this:

- [ ] Check if there's a connection to the database
- [ ] Check if there's a connection to the queue processor
- [ ] Check if the application can log

Do not attempt to read or write from the database, it's should be a very quick endpoint to respond

**Comment by devraj** [comment]
`docker` compose provides a way of performing `healthcheck` even at a [compose](https://docs.docker.com/engine/reference/builder/#healthcheck)  configuration:
```yaml
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  start_period: 40s
```
once this is completed we should move `compose` and `k8s` to use the endpoints. This is now pending #7
